name: Crystal CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Run tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: crystal spec

  deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v4
      - name: Install rsync
        run: apt-get update && apt-get install -y rsync
      - name: Create documentation
        run: crystal docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.

